version: '3.4'

services:
  kpfu-db-postgres:
    image: postgres:13
    container_name: kpfu-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 20s
      retries: 5
    volumes:
      - ./db-postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - kpfu-postgresql-data:/var/lib/postgresql/data
      - ./db-postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  kpfu-postgresql-data:

networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16