debug: ${SPRING_DEBUG:false}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
    url: ${POSTGRES_URL}?currentSchema=${POSTGRES_SCHEMA:data}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    jpa:
      show-sql: ${SPRING_DEBUG:false}
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          default_schema: ${POSTGRES_SCHEMA:data}
    liquibase:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master-postgres.xml
      default-schema: ${POSTGRES_SCHEMA:data}

ds:
  app:
    url: ${APP_URL}
    api-path: ${API_PATH}