debug: ${SPRING_DEBUG:false}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
    url: ${POSTGRES_URL}?currentSchema=${POSTGRES_SCHEMA:data}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    jpa:
      show-sql: ${SPRING_DEBUG:false}
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          default_schema: ${POSTGRES_SCHEMA:data}
    liquibase:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master-postgres.xml
      default-schema: ${POSTGRES_SCHEMA:data}

ds:
  app:
    url: ${APP_URL}
    api-path: ${API_PATH}
    auth:
      jwt:
        client:
          access-token-expiration: ${CLIENT_ACCESS_TOKEN_EXPIRATION_SEC}
          refresh-token-expiration: ${CLIENT_REFRESH_TOKEN_EXPIRATION_SEC}
          secret: ${CLIENT_JWT_SECRET}
        moderator:
          access-token-expiration: ${MODERATOR_ACCESS_TOKEN_EXPIRATION_SEC}
          refresh-token-expiration: ${MODERATOR_REFRESH_TOKEN_EXPIRATION_SEC}
          secret: ${MODERATOR_JWT_SECRET}
        admin:
          access-token-expiration: ${ADMIN_ACCESS_TOKEN_EXPIRATION_SEC}
          refresh-token-expiration: ${ADMIN_REFRESH_TOKEN_EXPIRATION_SEC}
          secret: ${ADMIN_JWT_SECRET}